name: flutter_altaoss
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.1.0
  firebase_storage: ^3.0.8


  google_maps_flutter: ^0.5.11
  location: ^2.3.5
  geolocator: ^5.1.3
  geocoder : ^0.2.1
  device_info: ^0.4.1+4

  month_picker_dialog: ^0.3.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  http: ^0.12.0+1
  share: ^0.6.0+1
  fluttertoast: ^3.0.4
  avatar_glow: ^0.1.0
  bottom_navy_bar: ^3.0.0
  shared_preferences: ^0.5.2
  image_picker: ^0.6.2+1
  circular_profile_avatar: ^1.0.2
  image_cropper: ^1.1.1
  url_launcher: 5.1.2
  cached_network_image: 1.1.3
  modal_progress_hud: ^0.1.3
  progress_dialog: ^1.2.0
  intl: 0.16.0

  local_auth: ^0.6.1
  preferences: ^5.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2+1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android:"launcher_icon"
  ios:true
  image_path:"assets/images/logo.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/profile.jpg
    - assets/images/photo_camera.png
    - assets/images/attendance.png
    - assets/images/empdirprofile.png
    - assets/images/empprofile.png
    - assets/images/listicon.png
    - assets/images/addprofile.jpg
    - assets/images/employeeinfo.png
    - assets/images/addprofile2.png
    - assets/images/addprofile3.jpg
    - assets/images/employeeadd.jpg
    - assets/images/myprofile.jpg
    - assets/images/alta.png
    - assets/images/updates.gif
    - assets/images/ourupdates.png
    - assets/images/newproject.png
    - assets/images/careers.png
    - assets/images/calen.png
    - assets/images/reim.png
    - assets/images/mypay.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
